### ISSUE TITLE
Error when installing pakage in laravel 6.x

### ISSUE THREAD

**Issue by Medboubazine** [paysera/lib-wallet-transfer-rest-client#6]
when executing 
`composer require paysera/lib-wallet-transfer-rest-client`
I get error mesage like picture
![image](https://user-images.githubusercontent.com/39988497/99586167-a063a080-29e7-11eb-8709-48608b3a10dd.png)

**Comment by vbartusevicius** [comment]
You are using guzzle-7, but this package is requiring guzzle-6. We do not support guzzle-6 at thr moment.
